; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:AVR128DA32]
platform = atmelmegaavr
board = AVR128DA32
framework = arduino
board_build.f_cpu = 24000000L
build_flags = -D USE_FLOATS=1 -D SERIAL_TX_BUFFER_SIZE=128 -D SERIAL_RX_BUFFER_SIZE=128 -D ENABLE_DEDICATED_SPI=1 -Wl,-u,vfprintf -lprintf_flt -lm

lib_deps =
    https://github.com/adafruit/Adafruit_BusIO.git
    Wire
    SPI
    https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library.git
    https://github.com/adafruit/Adafruit_GC9A01A.git
    https://github.com/adafruit/Adafruit-GFX-Library.git
;    https://github.com/mprograms/QMC5883LCompass.git
;    https://github.com/pololu/lis3mdl-arduino.git

; if you can't see the programmer, device manager, show hidden devices, look under ports
; Powershell Commands
; Get-WMIObject Win32_SerialPort
; [System.IO.Ports.SerialPort]::GetPortNames()
upload_command = D:/projects/jef/avrdude/avrdude -c jtag2updi -P COM10 -v -e -C D:/projects/jef/avrdude/avrdude.conf -p AVR128DA32 -U flash:w:$SOURCE:i -U osccfg:w:0x00:m -U syscfg0:w:0xE9:m -U syscfg1:w:0x00:m
